CREATE OR REPLACE VIEW QUALITY.DATA_QUALITY_SUMMARY AS

SELECT
    'ROW_COUNT_CHECKS' AS TEST_NAME,
    COUNT(*) AS FAILED_RECORDS,
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS TEST_STATUS
FROM QUALITY.TEST_ROW_COUNTS
WHERE ROW_COUNT < EXPECTED_MIN_ROWS

UNION ALL

SELECT
    'NULL_CHECKS',
    COUNT(*),
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END
FROM QUALITY.TEST_NULL_CHECKS
WHERE NULL_COUNT > 0

UNION ALL

SELECT
    'ACCEPTED_VALUES',
    COUNT(*),
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END
FROM QUALITY.TEST_ACCEPTED_VALUES

UNION ALL

SELECT
    'DUPLICATE_KEYS',
    COUNT(*),
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END
FROM QUALITY.TEST_DUPLICATE_KEYS

UNION ALL

SELECT
    'ATTRIBUTION_REVENUE_RECON',
    COUNT(*),
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END
FROM QUALITY.TEST_ATTRIBUTION_REVENUE_RECON
WHERE ABS(REVENUE_DIFFERENCE) > 1;
