CREATE OR REPLACE VIEW QUALITY.TEST_DUPLICATE_KEYS AS

SELECT
    'STG_CAMPAIGNS' AS TABLE_NAME,
    CAMPAIGN_ID,
    COUNT(*) AS RECORD_COUNT
FROM STAGING.STG_CAMPAIGNS
GROUP BY CAMPAIGN_ID
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'STG_CUSTOMERS',
    USER_ID,
    COUNT(*)
FROM STAGING.STG_CUSTOMERS
GROUP BY USER_ID
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'STG_CONVERSIONS',
    CONVERSION_ID,
    COUNT(*)
FROM STAGING.STG_CONVERSIONS
GROUP BY CONVERSION_ID
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'STG_MARKETING_TOUCHPOINTS',
    TOUCHPOINT_ID,
    COUNT(*)
FROM STAGING.STG_MARKETING_TOUCHPOINTS
GROUP BY TOUCHPOINT_ID
HAVING COUNT(*) > 1;
