CREATE OR REPLACE VIEW QUALITY.TEST_ATTRIBUTION_REVENUE_RECON AS

WITH attributed_revenue AS (

    SELECT
        'first_touch' AS ATTRIBUTION_MODEL,
        ROUND(SUM(ATTRIBUTED_REVENUE),2) AS ATTRIBUTED_REVENUE
    FROM INTERMEDIATE.INT_FIRST_TOUCH_ATTRIBUTION

    UNION ALL

    SELECT
        'last_touch',
        ROUND(SUM(ATTRIBUTED_REVENUE),2)
    FROM INTERMEDIATE.INT_LAST_TOUCH_ATTRIBUTION

    UNION ALL

    SELECT
        'linear',
        ROUND(SUM(ATTRIBUTED_REVENUE),2)
    FROM INTERMEDIATE.INT_LINEAR_ATTRIBUTION

),

conversion_revenue AS (

    SELECT
        ROUND(SUM(REVENUE),2) AS VALID_CONVERSION_REVENUE
    FROM (

        SELECT DISTINCT
            CONVERSION_ID,
            REVENUE
        FROM INTERMEDIATE.INT_USER_JOURNEY

    )

)

SELECT
    a.ATTRIBUTION_MODEL,
    a.ATTRIBUTED_REVENUE,
    c.VALID_CONVERSION_REVENUE,
    ROUND(
        a.ATTRIBUTED_REVENUE -
        c.VALID_CONVERSION_REVENUE,
        2
    ) AS REVENUE_DIFFERENCE
FROM attributed_revenue a
CROSS JOIN conversion_revenue c;
