CREATE OR REPLACE VIEW QUALITY.TEST_NULL_CHECKS AS

SELECT
    'STG_CAMPAIGNS' AS TABLE_NAME,
    'CAMPAIGN_ID' AS COLUMN_NAME,
    COUNT(*) AS NULL_COUNT
FROM STAGING.STG_CAMPAIGNS
WHERE CAMPAIGN_ID IS NULL

UNION ALL

SELECT
    'STG_CUSTOMERS',
    'USER_ID',
    COUNT(*)
FROM STAGING.STG_CUSTOMERS
WHERE USER_ID IS NULL

UNION ALL

SELECT
    'STG_MARKETING_TOUCHPOINTS',
    'TOUCHPOINT_ID',
    COUNT(*)
FROM STAGING.STG_MARKETING_TOUCHPOINTS
WHERE TOUCHPOINT_ID IS NULL

UNION ALL

SELECT
    'STG_CONVERSIONS',
    'CONVERSION_ID',
    COUNT(*)
FROM STAGING.STG_CONVERSIONS
WHERE CONVERSION_ID IS NULL;
