CREATE OR REPLACE VIEW QUALITY.TEST_ACCEPTED_VALUES AS

SELECT
    'STG_CAMPAIGNS' AS TABLE_NAME,
    'CHANNEL' AS COLUMN_NAME,
    CHANNEL AS INVALID_VALUE,
    COUNT(*) AS INVALID_COUNT
FROM STAGING.STG_CAMPAIGNS
WHERE CHANNEL NOT IN ('meta','google','affiliate','email','app')
GROUP BY CHANNEL

UNION ALL

SELECT
    'STG_MARKETING_TOUCHPOINTS',
    'EVENT_TYPE',
    EVENT_TYPE,
    COUNT(*)
FROM STAGING.STG_MARKETING_TOUCHPOINTS
WHERE EVENT_TYPE NOT IN
('impression','click','landing_page_visit','app_install')
GROUP BY EVENT_TYPE

UNION ALL

SELECT
    'STG_CONVERSIONS',
    'CONVERSION_TYPE',
    CONVERSION_TYPE,
    COUNT(*)
FROM STAGING.STG_CONVERSIONS
WHERE CONVERSION_TYPE NOT IN
('signup','deposit','purchase','subscription')
GROUP BY CONVERSION_TYPE;
