CREATE OR REPLACE VIEW QUALITY.TEST_ROW_COUNTS AS

SELECT 'RAW.CAMPAIGNS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 25 AS EXPECTED_MIN_ROWS
FROM RAW.CAMPAIGNS

UNION ALL

SELECT 'RAW.CUSTOMERS', COUNT(*), 500
FROM RAW.CUSTOMERS

UNION ALL

SELECT 'RAW.MARKETING_TOUCHPOINTS', COUNT(*), 5500
FROM RAW.MARKETING_TOUCHPOINTS

UNION ALL

SELECT 'RAW.CONVERSIONS', COUNT(*), 800
FROM RAW.CONVERSIONS

UNION ALL

SELECT 'RAW.AD_SPEND', COUNT(*), 1000
FROM RAW.AD_SPEND;
