SELECT
    ATTRIBUTION_MODEL,
    ROUND(SUM(ATTRIBUTED_REVENUE), 2) AS ATTRIBUTED_REVENUE,
    SUM(ATTRIBUTED_CONVERSIONS) AS ATTRIBUTED_CONVERSIONS
FROM ANALYTICS.FCT_ATTRIBUTION_PERFORMANCE
GROUP BY ATTRIBUTION_MODEL
ORDER BY ATTRIBUTION_MODEL;


----- Compare first-touch, last-touch and linear attribution outcomes.Show more lines ----
