SELECT
    ATTRIBUTION_MODEL,
    CHANNEL,
    ROUND(SUM(ATTRIBUTED_REVENUE), 2) AS TOTAL_ATTRIBUTED_REVENUE,
    SUM(ATTRIBUTED_CONVERSIONS) AS TOTAL_ATTRIBUTED_CONVERSIONS,
    ROUND(
        SUM(ATTRIBUTED_REVENUE) /
        NULLIF(SUM(TOTAL_SPEND), 0),
        2
    ) AS ATTRIBUTED_ROAS
FROM ANALYTICS.FCT_ATTRIBUTION_PERFORMANCE
GROUP BY
    ATTRIBUTION_MODEL,
    CHANNEL
ORDER BY
    ATTRIBUTION_MODEL,
    TOTAL_ATTRIBUTED_REVENUE DESC;


---- Understand channel contribution under different attribution models
