SELECT
    CHANNEL,
    TOTAL_SPEND,
    FIRST_TOUCH_REVENUE,
    LAST_TOUCH_REVENUE,
    LINEAR_ATTRIBUTED_REVENUE,
    FIRST_TOUCH_ROAS,
    LAST_TOUCH_ROAS,
    LINEAR_ROAS
FROM ANALYTICS.FCT_CHANNEL_ATTRIBUTION
ORDER BY LINEAR_ROAS DESC;


-----Compare Meta, Google, Affiliate, Email and App channel performance----
