SELECT
    TOTAL_TOUCHPOINTS,
    COUNT(DISTINCT CONVERSION_ID) AS CONVERSIONS
FROM INTERMEDIATE.INT_USER_JOURNEY
GROUP BY TOTAL_TOUCHPOINTS
ORDER BY TOTAL_TOUCHPOINTS;


---- Analyze how many touchpoints customers typically have before converting ----
