SELECT
    CHANNEL,
    SUM(LINEAR_ATTRIBUTED_REVENUE) AS TOTAL_REVENUE,
    SUM(LINEAR_ATTRIBUTED_CONVERSIONS) AS TOTAL_CONVERSIONS,
    ROUND(
        SUM(LINEAR_ATTRIBUTED_REVENUE) /
        NULLIF(SUM(TOTAL_SPEND),0),
        2
    ) AS ROAS
FROM ANALYTICS.FCT_CHANNEL_ATTRIBUTION
GROUP BY CHANNEL
ORDER BY TOTAL_REVENUE DESC;


----- Find the channels contributing most revenue and conversions.Show more lines----
