SELECT
    CAMPAIGN_ID,
    CAMPAIGN_NAME,
    CHANNEL,
    TOTAL_SPEND,
    LINEAR_ATTRIBUTED_REVENUE,
    LINEAR_ROAS,
    COST_PER_LINEAR_ATTRIBUTED_CONVERSION
FROM ANALYTICS.FCT_CAMPAIGN_MEASUREMENT
ORDER BY LINEAR_ROAS DESC
LIMIT 10;

---- Identify the highest-performing campaigns based on attributed ROAS------
