CREATE OR REPLACE VIEW INTERMEDIATE.INT_FIRST_TOUCH_ATTRIBUTION AS

SELECT
    CONVERSION_ID,
    USER_ID,
    TOUCHPOINT_ID,
    CAMPAIGN_ID,
    CHANNEL,
    EVENT_TYPE,
    TOUCHPOINT_TIME,
    CONVERSION_TIME,
    CONVERSION_TYPE,
    REVENUE,

    TOUCHPOINT_SEQUENCE,
    TOTAL_TOUCHPOINTS,

    'first_touch' AS ATTRIBUTION_MODEL,

    REVENUE AS ATTRIBUTED_REVENUE,

    1 AS ATTRIBUTION_CREDIT

FROM INTERMEDIATE.INT_USER_JOURNEY

WHERE TOUCHPOINT_SEQUENCE = 1;
