CREATE OR REPLACE VIEW INTERMEDIATE.INT_USER_JOURNEY AS

SELECT

    c.CONVERSION_ID,
    c.USER_ID,

    t.TOUCHPOINT_ID,
    t.CAMPAIGN_ID,
    t.CHANNEL,
    t.EVENT_TYPE,

    t.TOUCHPOINT_TIME,
    c.CONVERSION_TIME,

    c.CONVERSION_TYPE,
    c.REVENUE,

    ROW_NUMBER() OVER (
        PARTITION BY c.CONVERSION_ID
        ORDER BY t.TOUCHPOINT_TIME
    ) AS TOUCHPOINT_SEQUENCE,

    COUNT(*) OVER (
        PARTITION BY c.CONVERSION_ID
    ) AS TOTAL_TOUCHPOINTS

FROM STAGING.STG_CONVERSIONS c

INNER JOIN STAGING.STG_MARKETING_TOUCHPOINTS t
    ON c.USER_ID = t.USER_ID

WHERE t.TOUCHPOINT_TIME <= c.CONVERSION_TIME;
