CREATE OR REPLACE VIEW INTERMEDIATE.INT_LINEAR_ATTRIBUTION AS

SELECT
    CONVERSION_ID,
    USER_ID,
    TOUCHPOINT_ID,
    CAMPAIGN_ID,
    CHANNEL,
    EVENT_TYPE,
    TOUCHPOINT_TIME,
    CONVERSION_TIME,
    CONVERSION_TYPE,
    REVENUE,

    TOUCHPOINT_SEQUENCE,
    TOTAL_TOUCHPOINTS,

    'linear' AS ATTRIBUTION_MODEL,

    ROUND(
        REVENUE / NULLIF(TOTAL_TOUCHPOINTS, 0),
        2
    ) AS ATTRIBUTED_REVENUE,

    ROUND(
        1.0 / NULLIF(TOTAL_TOUCHPOINTS, 0),
        4
    ) AS ATTRIBUTION_CREDIT

FROM INTERMEDIATE.INT_USER_JOURNEY;
