CREATE OR REPLACE VIEW STAGING.STG_MARKETING_TOUCHPOINTS AS

SELECT
    TOUCHPOINT_ID,
    USER_ID,
    CAMPAIGN_ID,
    LOWER(CHANNEL) AS CHANNEL,
    TOUCHPOINT_TIME,
    LOWER(EVENT_TYPE) AS EVENT_TYPE,
    LOWER(DEVICE_TYPE) AS DEVICE_TYPE
FROM RAW.MARKETING_TOUCHPOINTS;
