CREATE OR REPLACE VIEW STAGING.STG_CAMPAIGNS AS

SELECT
    CAMPAIGN_ID,
    TRIM(CAMPAIGN_NAME) AS CAMPAIGN_NAME,
    LOWER(TRIM(CHANNEL)) AS CHANNEL,
    CAMPAIGN_START_DATE,
    CAMPAIGN_END_DATE,
    LOWER(TRIM(CAMPAIGN_OBJECTIVE)) AS CAMPAIGN_OBJECTIVE,
    BUDGET
FROM RAW.CAMPAIGNS;
