-- Create schemas for layered Snowflake architecture

USE DATABASE MARKETING_ATTRIBUTION_DB;

CREATE SCHEMA IF NOT EXISTS RAW;

CREATE SCHEMA IF NOT EXISTS STAGING;

CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;

CREATE SCHEMA IF NOT EXISTS QUALITY;
